// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package datamodels

import (
	"ai-agent/model/datamodels"

	mock "github.com/stretchr/testify/mock"
)

// NewMockGemini creates a new instance of MockGemini. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGemini(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGemini {
	mock := &MockGemini{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGemini is an autogenerated mock type for the Gemini type
type MockGemini struct {
	mock.Mock
}

type MockGemini_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGemini) EXPECT() *MockGemini_Expecter {
	return &MockGemini_Expecter{mock: &_m.Mock}
}

// Chat provides a mock function for the type MockGemini
func (_mock *MockGemini) Chat(userInput string, h []datamodels.HistoryContext) (*datamodels.HistoryContext, error) {
	ret := _mock.Called(userInput, h)

	if len(ret) == 0 {
		panic("no return value specified for Chat")
	}

	var r0 *datamodels.HistoryContext
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, []datamodels.HistoryContext) (*datamodels.HistoryContext, error)); ok {
		return returnFunc(userInput, h)
	}
	if returnFunc, ok := ret.Get(0).(func(string, []datamodels.HistoryContext) *datamodels.HistoryContext); ok {
		r0 = returnFunc(userInput, h)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*datamodels.HistoryContext)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, []datamodels.HistoryContext) error); ok {
		r1 = returnFunc(userInput, h)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGemini_Chat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Chat'
type MockGemini_Chat_Call struct {
	*mock.Call
}

// Chat is a helper method to define mock.On call
//   - userInput string
//   - h []datamodels.HistoryContext
func (_e *MockGemini_Expecter) Chat(userInput interface{}, h interface{}) *MockGemini_Chat_Call {
	return &MockGemini_Chat_Call{Call: _e.mock.On("Chat", userInput, h)}
}

func (_c *MockGemini_Chat_Call) Run(run func(userInput string, h []datamodels.HistoryContext)) *MockGemini_Chat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []datamodels.HistoryContext
		if args[1] != nil {
			arg1 = args[1].([]datamodels.HistoryContext)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGemini_Chat_Call) Return(historyContext *datamodels.HistoryContext, err error) *MockGemini_Chat_Call {
	_c.Call.Return(historyContext, err)
	return _c
}

func (_c *MockGemini_Chat_Call) RunAndReturn(run func(userInput string, h []datamodels.HistoryContext) (*datamodels.HistoryContext, error)) *MockGemini_Chat_Call {
	_c.Call.Return(run)
	return _c
}
