version: "2"
linters:
  enable:
    - bodyclose
    - errorlint
    - goconst
    - gocritic
    - gocyclo
    - revive
    - staticcheck
    - unconvert
    - unparam
  settings:
    revive:
      rules:
        - name: package-comments
          disabled: true
        - name: dot-imports
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - aiat
          - containedctx
          - contextcheck
          - cyclop
          - decorder
          - depguard
          - dogsled
          - dupimport
          - dupl
          - durationcheck
          - err113
          - errcheck
          - errchkjson
          - errname
          - errorlint
          - execinquery
          - exhaustive
          - exhaustivestruct
          - exhaustruct
          - exportloopref
          - forbidigo
          - forcetypeassert
          - funlen
          - ginkgo-focus
          - ginkgo-no-focused-describe
          - ginkgo-prefer-async-matchers
          - ginkgo-suite-with-name
          - gocheckcompilerdirectives
          - gochecknoglobals
          - gochecknoinits
          - gocognit
          - goconst
          - gocritic
          - gocyclo
          - godot
          - godox
          - goheader
          - gomega-must-not-be-called-in-init
          - gomega-return-value-must-be-checked
          - gomega-wrong-matcher
          - gomoddirectives
          - gomodguard
          - goprintffuncname
          - gosec
          - grouper
          - importas
          - interfacebloat
          - ireturn
          - lll
          - loggercheck
          - maintidx
          - makezero
          - maligned
          - misspell
          - mnd
          - musttag
          - nakedret
          - nestif
          - nilerr
          - nilnil
          - nlreturn
          - noctx
          - nolintlint
          - nonamedreturns
          - nosprintfhostport
          - paralleltest
          - predeclared
          - promlinter
          - protogetter
          - reassign
          - revive
          - rowserrcheck
          - sqlclosecheck
          - staticcheck
          - tagliatelle
          - tenv
          - testableexamples
          - testpackage
          - thelper
          - tparallel
          - unconvert
          - unparam
          - unused
          - usestdlibvars
          - wastedassign
          - whitespace
          - wrapcheck
          - wsl
          - zerologlint
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/khaled.kadoura/golang-crud-ai-agentcontroller-lambda
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - _test\.go
