run:
  timeout: 5m
linters:
  enable:
    - govet
    - revive
    - staticcheck
    - goimports
    - unconvert
    - typecheck
    - unused
    - gosimple
    - ineffassign
    - bodyclose
    - stylecheck
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - errorlint
    - unparam
linters-settings:
  goimports:
    local-prefixes: github.com/khaled.kadoura/golang-crud-ai-agentcontroller-lambda
  revive:
    rules:
      - name: package-comments
        disabled: true
      - name: dot-imports
        disabled: true
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - goconst
        - gosec
        - noctx
        - testpackage
        - paralleltest
        - tparallel
        - aiat
        - exhaustruct
        - forcetypeassert
        - nlreturn
        - wrapcheck
        - wsl
        - dupl
        - nestif
        - godot
        - godox
        - gochecknoglobals
        - gochecknoinits
        - gocognit
        - gocyclo
        - goerr113
        - gomnd
        - lll
        - nakedret
        - testableexamples
        - unparam
        - whitespace
        - ginkgo-focus
        - ginkgo-no-focused-describe
        - ginkgo-prefer-async-matchers
        - ginkgo-suite-with-name
        - gomega-must-not-be-called-in-init
        - gomega-return-value-must-be-checked
        - gomega-wrong-matcher
        - promlinter
        - reassign
        - rowserrcheck
        - sqlclosecheck
        - wastedassign
        - execinquery
        - makezero
        - nilerr
        - contextcheck
        - errchkjson
        - errname
        - errorlint
        - exhaustive
        - exportloopref
        - gosec
        - interfacebloat
        - musttag
        - nonamedreturns
        - nosprintfhostport
        - predeclared
        - tenv
        - thelper
        - usestdlibvars
        - zerologlint
        - containedctx
        - cyclop
        - decorder
        - depguard
        - dogsled
        - dupimport
        - durationcheck
        - errcheck
        - exhaustive
        - exhaustivestruct
        - forbidigo
        - funlen
        - gci
        - gocheckcompilerdirectives
        - goconst
        - gocritic
        - gocyclo
        - godot
        - gofumpt
        - goheader
        - goimports
        - gomoddirectives
        - gomodguard
        - goprintffuncname
        - gosec
        - grouper
        - importas
        - interfacebloat
        - ireturn
        - lll
        - loggercheck
        - maintidx
        - maligned
        - misspell
        - nakedret
        - nestif
        - nilnil
        - nlreturn
        - noctx
        - nolintlint
        - nonamedreturns
        - nosprintfhostport
        - paralleltest
        - predeclared
        - promlinter
        - protogetter
        - reassign
        - revive
        - rowserrcheck
        - sqlclosecheck
        - stylecheck
        - tagliatelle
        - tenv
        - testableexamples
        - testpackage
        - thelper
        - tparallel
        - unconvert
        - unparam
        - unused
        - usestdlibvars
        - wastedassign
        - whitespace
        - wrapcheck
        - wsl
        - zerologlint