all: true
recursive: true

packages:
  ai-agent/interface:
    config:
      all: true
      dir: "{{.InterfaceDir}}/mocks"
      filename: "mocks_{{.InterfaceName}}.go"
      structname: "{{.Mock}}{{.InterfaceName}}"
