all: true
recursive: true

packages:
  ai-agent/model/datamodels:
    config:
      all: true
      dir: "{{.InterfaceDir}}/mocks"
      filename: "mocks_{{.InterfaceName}}.go"
      structname: "{{.Mock}}{{.InterfaceName}}"
  ai-agent/model/servicemodels:
    config:
      all: true
      dir: "{{.InterfaceDir}}/mocks"
      filename: "mocks_{{.InterfaceName}}.go"
      structname: "{{.Mock}}{{.InterfaceName}}"
