AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: ai-agent lambda

Globals:
  Function:
    Timeout: 100

Resources:
  AiAgentServerlessAPI:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: ./cmd
      Runtime: go1.x
      MemorySize: 1024
      Environment:
        Variables:
          GIN_MODE: debug
          ENVIRONMENT: test
          AWS_REGION: eu-central-1
          LOG_LEVEL: debug
          SECRETS_ARN: ai-agent-lambda-test-secret-secrets
          DYNAMODB_TABLE_NAME: ai-agent-lambda-test-table
          DYNAMODB_USER_ID_KEY: user_id
          DYNAMODB_TIMESTAMP_KEY: timestamp

