// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"ai-agent/controller/health"
	"ai-agent/router"

	"github.com/gin-gonic/gin"
	"github.com/google/wire"
)

// Injectors from Wire.go:

func InitializeServer() *Server {
	engine := NewGinEngine()
	controllerController := health.New()
	routerRouter := router.New(engine, controllerController)
	serverServer := New(engine, routerRouter)
	return serverServer
}

// Wire.go:

func NewGinEngine() *gin.Engine {
	return gin.New()
}

var ProviderSet = wire.NewSet(
	NewGinEngine, health.New, router.New, New,
)
