// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"ai-agent/controller/agentcontroller"
	"ai-agent/controller/healthcontroller"
	"ai-agent/model/aiagentmodel"
	"ai-agent/model/geminimodel"
	"ai-agent/pkg/geminipkg"
	"ai-agent/pkg/secretspkg"
	"ai-agent/router"
	"ai-agent/service/aiagent"
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"os"
)

// Injectors from Wire.go:

func InitializeServer() (*Server, error) {
	engine := NewGinEngine()
	controller := healthcontroller.New()
	appConfig, err := secretspkg.New()
	if err != nil {
		return nil, err
	}
	gemini, err := geminipkg.New(appConfig)
	if err != nil {
		return nil, err
	}
	service := aiagent.New(gemini)
	agentcontrollerController := agentcontroller.New(service)
	routerRouter := router.New(engine, controller, agentcontrollerController)
	server := New(engine, routerRouter)
	return server, nil
}

// Wire.go:

func NewGinEngine() *gin.Engine {
	gin.SetMode(os.Getenv("GIN_MODE"))

	return gin.New()
}

var ProviderSet = wire.NewSet(
	NewGinEngine,
	New, healthcontroller.New, wire.Bind(new(geminimodel.Gemini), new(*geminipkg.Gemini)), agentcontroller.New, wire.Bind(new(aiagentmodel.AgentService), new(*aiagent.Service)), router.New, geminipkg.New, secretspkg.New, aiagent.New,
)
