// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package servicemodels

import (
	"ai-agent/model/datamodels"

	mock "github.com/stretchr/testify/mock"
)

// NewMockPersistence creates a new instance of MockPersistence. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPersistence(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPersistence {
	mock := &MockPersistence{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPersistence is an autogenerated mock type for the Persistence type
type MockPersistence struct {
	mock.Mock
}

type MockPersistence_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPersistence) EXPECT() *MockPersistence_Expecter {
	return &MockPersistence_Expecter{mock: &_m.Mock}
}

// GetUserHistory provides a mock function for the type MockPersistence
func (_mock *MockPersistence) GetUserHistory(id string) ([]datamodels.Chat, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserHistory")
	}

	var r0 []datamodels.Chat
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]datamodels.Chat, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []datamodels.Chat); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]datamodels.Chat)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPersistence_GetUserHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserHistory'
type MockPersistence_GetUserHistory_Call struct {
	*mock.Call
}

// GetUserHistory is a helper method to define mock.On call
//   - id string
func (_e *MockPersistence_Expecter) GetUserHistory(id interface{}) *MockPersistence_GetUserHistory_Call {
	return &MockPersistence_GetUserHistory_Call{Call: _e.mock.On("GetUserHistory", id)}
}

func (_c *MockPersistence_GetUserHistory_Call) Run(run func(id string)) *MockPersistence_GetUserHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPersistence_GetUserHistory_Call) Return(chats []datamodels.Chat, err error) *MockPersistence_GetUserHistory_Call {
	_c.Call.Return(chats, err)
	return _c
}

func (_c *MockPersistence_GetUserHistory_Call) RunAndReturn(run func(id string) ([]datamodels.Chat, error)) *MockPersistence_GetUserHistory_Call {
	_c.Call.Return(run)
	return _c
}

// StoreConversation provides a mock function for the type MockPersistence
func (_mock *MockPersistence) StoreConversation(userID string, history *datamodels.HistoryContext) error {
	ret := _mock.Called(userID, history)

	if len(ret) == 0 {
		panic("no return value specified for StoreConversation")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, *datamodels.HistoryContext) error); ok {
		r0 = returnFunc(userID, history)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPersistence_StoreConversation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoreConversation'
type MockPersistence_StoreConversation_Call struct {
	*mock.Call
}

// StoreConversation is a helper method to define mock.On call
//   - userID string
//   - history *datamodels.HistoryContext
func (_e *MockPersistence_Expecter) StoreConversation(userID interface{}, history interface{}) *MockPersistence_StoreConversation_Call {
	return &MockPersistence_StoreConversation_Call{Call: _e.mock.On("StoreConversation", userID, history)}
}

func (_c *MockPersistence_StoreConversation_Call) Run(run func(userID string, history *datamodels.HistoryContext)) *MockPersistence_StoreConversation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *datamodels.HistoryContext
		if args[1] != nil {
			arg1 = args[1].(*datamodels.HistoryContext)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPersistence_StoreConversation_Call) Return(err error) *MockPersistence_StoreConversation_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPersistence_StoreConversation_Call) RunAndReturn(run func(userID string, history *datamodels.HistoryContext) error) *MockPersistence_StoreConversation_Call {
	_c.Call.Return(run)
	return _c
}
