// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package servicemodels

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockAgentService creates a new instance of MockAgentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAgentService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAgentService {
	mock := &MockAgentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAgentService is an autogenerated mock type for the AgentService type
type MockAgentService struct {
	mock.Mock
}

type MockAgentService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAgentService) EXPECT() *MockAgentService_Expecter {
	return &MockAgentService_Expecter{mock: &_m.Mock}
}

// SendMessageWithHistory provides a mock function for the type MockAgentService
func (_mock *MockAgentService) SendMessageWithHistory(userID string, message string) (string, error) {
	ret := _mock.Called(userID, message)

	if len(ret) == 0 {
		panic("no return value specified for SendMessageWithHistory")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return returnFunc(userID, message)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = returnFunc(userID, message)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(userID, message)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAgentService_SendMessageWithHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessageWithHistory'
type MockAgentService_SendMessageWithHistory_Call struct {
	*mock.Call
}

// SendMessageWithHistory is a helper method to define mock.On call
//   - userID string
//   - message string
func (_e *MockAgentService_Expecter) SendMessageWithHistory(userID interface{}, message interface{}) *MockAgentService_SendMessageWithHistory_Call {
	return &MockAgentService_SendMessageWithHistory_Call{Call: _e.mock.On("SendMessageWithHistory", userID, message)}
}

func (_c *MockAgentService_SendMessageWithHistory_Call) Run(run func(userID string, message string)) *MockAgentService_SendMessageWithHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAgentService_SendMessageWithHistory_Call) Return(s string, err error) *MockAgentService_SendMessageWithHistory_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockAgentService_SendMessageWithHistory_Call) RunAndReturn(run func(userID string, message string) (string, error)) *MockAgentService_SendMessageWithHistory_Call {
	_c.Call.Return(run)
	return _c
}
