// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockAgentService is an autogenerated mock type for the AgentService type
type MockAgentService struct {
	mock.Mock
}

type MockAgentService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAgentService) EXPECT() *MockAgentService_Expecter {
	return &MockAgentService_Expecter{mock: &_m.Mock}
}

// SendMessageWithHistory provides a mock function with given fields: userID, message
func (_m *MockAgentService) SendMessageWithHistory(userID string, message string) (string, error) {
	ret := _m.Called(userID, message)

	if len(ret) == 0 {
		panic("no return value specified for SendMessageWithHistory")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return rf(userID, message)
	}
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(userID, message)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(userID, message)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAgentService_SendMessageWithHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessageWithHistory'
type MockAgentService_SendMessageWithHistory_Call struct {
	*mock.Call
}

// SendMessageWithHistory is a helper method to define mock.On call
//   - userID string
//   - message string
func (_e *MockAgentService_Expecter) SendMessageWithHistory(userID interface{}, message interface{}) *MockAgentService_SendMessageWithHistory_Call {
	return &MockAgentService_SendMessageWithHistory_Call{Call: _e.mock.On("SendMessageWithHistory", userID, message)}
}

func (_c *MockAgentService_SendMessageWithHistory_Call) Run(run func(userID string, message string)) *MockAgentService_SendMessageWithHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockAgentService_SendMessageWithHistory_Call) Return(_a0 string, _a1 error) *MockAgentService_SendMessageWithHistory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAgentService_SendMessageWithHistory_Call) RunAndReturn(run func(string, string) (string, error)) *MockAgentService_SendMessageWithHistory_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAgentService creates a new instance of MockAgentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAgentService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAgentService {
	mock := &MockAgentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
