// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package _interface

import (
	"ai-agent/entity"

	mock "github.com/stretchr/testify/mock"
)

// NewMockBookRepo creates a new instance of MockBookRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBookRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBookRepo {
	mock := &MockBookRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBookRepo is an autogenerated mock type for the BookRepo type
type MockBookRepo struct {
	mock.Mock
}

type MockBookRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBookRepo) EXPECT() *MockBookRepo_Expecter {
	return &MockBookRepo_Expecter{mock: &_m.Mock}
}

// InsertBookIfNotExists provides a mock function for the type MockBookRepo
func (_mock *MockBookRepo) InsertBookIfNotExists(book *entity.BookEntity) error {
	ret := _mock.Called(book)

	if len(ret) == 0 {
		panic("no return value specified for InsertBookIfNotExists")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*entity.BookEntity) error); ok {
		r0 = returnFunc(book)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBookRepo_InsertBookIfNotExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertBookIfNotExists'
type MockBookRepo_InsertBookIfNotExists_Call struct {
	*mock.Call
}

// InsertBookIfNotExists is a helper method to define mock.On call
//   - book *entity.BookEntity
func (_e *MockBookRepo_Expecter) InsertBookIfNotExists(book interface{}) *MockBookRepo_InsertBookIfNotExists_Call {
	return &MockBookRepo_InsertBookIfNotExists_Call{Call: _e.mock.On("InsertBookIfNotExists", book)}
}

func (_c *MockBookRepo_InsertBookIfNotExists_Call) Run(run func(book *entity.BookEntity)) *MockBookRepo_InsertBookIfNotExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *entity.BookEntity
		if args[0] != nil {
			arg0 = args[0].(*entity.BookEntity)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBookRepo_InsertBookIfNotExists_Call) Return(err error) *MockBookRepo_InsertBookIfNotExists_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBookRepo_InsertBookIfNotExists_Call) RunAndReturn(run func(book *entity.BookEntity) error) *MockBookRepo_InsertBookIfNotExists_Call {
	_c.Call.Return(run)
	return _c
}

// SearchForRelevantBook provides a mock function for the type MockBookRepo
func (_mock *MockBookRepo) SearchForRelevantBook(embedding []float32) ([]entity.BookEntity, error) {
	ret := _mock.Called(embedding)

	if len(ret) == 0 {
		panic("no return value specified for SearchForRelevantBook")
	}

	var r0 []entity.BookEntity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]float32) ([]entity.BookEntity, error)); ok {
		return returnFunc(embedding)
	}
	if returnFunc, ok := ret.Get(0).(func([]float32) []entity.BookEntity); ok {
		r0 = returnFunc(embedding)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.BookEntity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]float32) error); ok {
		r1 = returnFunc(embedding)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookRepo_SearchForRelevantBook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchForRelevantBook'
type MockBookRepo_SearchForRelevantBook_Call struct {
	*mock.Call
}

// SearchForRelevantBook is a helper method to define mock.On call
//   - embedding []float32
func (_e *MockBookRepo_Expecter) SearchForRelevantBook(embedding interface{}) *MockBookRepo_SearchForRelevantBook_Call {
	return &MockBookRepo_SearchForRelevantBook_Call{Call: _e.mock.On("SearchForRelevantBook", embedding)}
}

func (_c *MockBookRepo_SearchForRelevantBook_Call) Run(run func(embedding []float32)) *MockBookRepo_SearchForRelevantBook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []float32
		if args[0] != nil {
			arg0 = args[0].([]float32)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBookRepo_SearchForRelevantBook_Call) Return(bookEntitys []entity.BookEntity, err error) *MockBookRepo_SearchForRelevantBook_Call {
	_c.Call.Return(bookEntitys, err)
	return _c
}

func (_c *MockBookRepo_SearchForRelevantBook_Call) RunAndReturn(run func(embedding []float32) ([]entity.BookEntity, error)) *MockBookRepo_SearchForRelevantBook_Call {
	_c.Call.Return(run)
	return _c
}
