// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package _interface

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockEmbeddingModel creates a new instance of MockEmbeddingModel. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmbeddingModel(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmbeddingModel {
	mock := &MockEmbeddingModel{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEmbeddingModel is an autogenerated mock type for the EmbeddingModel type
type MockEmbeddingModel struct {
	mock.Mock
}

type MockEmbeddingModel_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEmbeddingModel) EXPECT() *MockEmbeddingModel_Expecter {
	return &MockEmbeddingModel_Expecter{mock: &_m.Mock}
}

// EmbedSearchDocument provides a mock function for the type MockEmbeddingModel
func (_mock *MockEmbeddingModel) EmbedSearchDocument(text string) ([]float32, error) {
	ret := _mock.Called(text)

	if len(ret) == 0 {
		panic("no return value specified for EmbedSearchDocument")
	}

	var r0 []float32
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]float32, error)); ok {
		return returnFunc(text)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []float32); ok {
		r0 = returnFunc(text)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]float32)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(text)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEmbeddingModel_EmbedSearchDocument_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EmbedSearchDocument'
type MockEmbeddingModel_EmbedSearchDocument_Call struct {
	*mock.Call
}

// EmbedSearchDocument is a helper method to define mock.On call
//   - text string
func (_e *MockEmbeddingModel_Expecter) EmbedSearchDocument(text interface{}) *MockEmbeddingModel_EmbedSearchDocument_Call {
	return &MockEmbeddingModel_EmbedSearchDocument_Call{Call: _e.mock.On("EmbedSearchDocument", text)}
}

func (_c *MockEmbeddingModel_EmbedSearchDocument_Call) Run(run func(text string)) *MockEmbeddingModel_EmbedSearchDocument_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEmbeddingModel_EmbedSearchDocument_Call) Return(float32s []float32, err error) *MockEmbeddingModel_EmbedSearchDocument_Call {
	_c.Call.Return(float32s, err)
	return _c
}

func (_c *MockEmbeddingModel_EmbedSearchDocument_Call) RunAndReturn(run func(text string) ([]float32, error)) *MockEmbeddingModel_EmbedSearchDocument_Call {
	_c.Call.Return(run)
	return _c
}

// EmbedSearchQuery provides a mock function for the type MockEmbeddingModel
func (_mock *MockEmbeddingModel) EmbedSearchQuery(query string) ([]float32, error) {
	ret := _mock.Called(query)

	if len(ret) == 0 {
		panic("no return value specified for EmbedSearchQuery")
	}

	var r0 []float32
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]float32, error)); ok {
		return returnFunc(query)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []float32); ok {
		r0 = returnFunc(query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]float32)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEmbeddingModel_EmbedSearchQuery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EmbedSearchQuery'
type MockEmbeddingModel_EmbedSearchQuery_Call struct {
	*mock.Call
}

// EmbedSearchQuery is a helper method to define mock.On call
//   - query string
func (_e *MockEmbeddingModel_Expecter) EmbedSearchQuery(query interface{}) *MockEmbeddingModel_EmbedSearchQuery_Call {
	return &MockEmbeddingModel_EmbedSearchQuery_Call{Call: _e.mock.On("EmbedSearchQuery", query)}
}

func (_c *MockEmbeddingModel_EmbedSearchQuery_Call) Run(run func(query string)) *MockEmbeddingModel_EmbedSearchQuery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEmbeddingModel_EmbedSearchQuery_Call) Return(float32s []float32, err error) *MockEmbeddingModel_EmbedSearchQuery_Call {
	_c.Call.Return(float32s, err)
	return _c
}

func (_c *MockEmbeddingModel_EmbedSearchQuery_Call) RunAndReturn(run func(query string) ([]float32, error)) *MockEmbeddingModel_EmbedSearchQuery_Call {
	_c.Call.Return(run)
	return _c
}
