// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package _interface

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockAgentUsecase creates a new instance of MockAgentUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAgentUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAgentUsecase {
	mock := &MockAgentUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAgentUsecase is an autogenerated mock type for the AgentUsecase type
type MockAgentUsecase struct {
	mock.Mock
}

type MockAgentUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAgentUsecase) EXPECT() *MockAgentUsecase_Expecter {
	return &MockAgentUsecase_Expecter{mock: &_m.Mock}
}

// SendMessageWithHistory provides a mock function for the type MockAgentUsecase
func (_mock *MockAgentUsecase) SendMessageWithHistory(userID string, message string, systemPrompt string) (string, error) {
	ret := _mock.Called(userID, message, systemPrompt)

	if len(ret) == 0 {
		panic("no return value specified for SendMessageWithHistory")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string) (string, error)); ok {
		return returnFunc(userID, message, systemPrompt)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, string) string); ok {
		r0 = returnFunc(userID, message, systemPrompt)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = returnFunc(userID, message, systemPrompt)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAgentUsecase_SendMessageWithHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessageWithHistory'
type MockAgentUsecase_SendMessageWithHistory_Call struct {
	*mock.Call
}

// SendMessageWithHistory is a helper method to define mock.On call
//   - userID string
//   - message string
//   - systemPrompt string
func (_e *MockAgentUsecase_Expecter) SendMessageWithHistory(userID interface{}, message interface{}, systemPrompt interface{}) *MockAgentUsecase_SendMessageWithHistory_Call {
	return &MockAgentUsecase_SendMessageWithHistory_Call{Call: _e.mock.On("SendMessageWithHistory", userID, message, systemPrompt)}
}

func (_c *MockAgentUsecase_SendMessageWithHistory_Call) Run(run func(userID string, message string, systemPrompt string)) *MockAgentUsecase_SendMessageWithHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAgentUsecase_SendMessageWithHistory_Call) Return(s string, err error) *MockAgentUsecase_SendMessageWithHistory_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockAgentUsecase_SendMessageWithHistory_Call) RunAndReturn(run func(userID string, message string, systemPrompt string) (string, error)) *MockAgentUsecase_SendMessageWithHistory_Call {
	_c.Call.Return(run)
	return _c
}
