// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package _interface

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockDomainRepo creates a new instance of MockDomainRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDomainRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDomainRepo {
	mock := &MockDomainRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDomainRepo is an autogenerated mock type for the DomainRepo type
type MockDomainRepo struct {
	mock.Mock
}

type MockDomainRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDomainRepo) EXPECT() *MockDomainRepo_Expecter {
	return &MockDomainRepo_Expecter{mock: &_m.Mock}
}

// GetDomainInstructions provides a mock function for the type MockDomainRepo
func (_mock *MockDomainRepo) GetDomainInstructions(name string) (string, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetDomainInstructions")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDomainRepo_GetDomainInstructions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDomainInstructions'
type MockDomainRepo_GetDomainInstructions_Call struct {
	*mock.Call
}

// GetDomainInstructions is a helper method to define mock.On call
//   - name string
func (_e *MockDomainRepo_Expecter) GetDomainInstructions(name interface{}) *MockDomainRepo_GetDomainInstructions_Call {
	return &MockDomainRepo_GetDomainInstructions_Call{Call: _e.mock.On("GetDomainInstructions", name)}
}

func (_c *MockDomainRepo_GetDomainInstructions_Call) Run(run func(name string)) *MockDomainRepo_GetDomainInstructions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDomainRepo_GetDomainInstructions_Call) Return(s string, err error) *MockDomainRepo_GetDomainInstructions_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockDomainRepo_GetDomainInstructions_Call) RunAndReturn(run func(name string) (string, error)) *MockDomainRepo_GetDomainInstructions_Call {
	_c.Call.Return(run)
	return _c
}
