// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package _interface

import (
	"ai-agent/entity"

	mock "github.com/stretchr/testify/mock"
)

// NewMockChatRepo creates a new instance of MockChatRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChatRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChatRepo {
	mock := &MockChatRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChatRepo is an autogenerated mock type for the ChatRepo type
type MockChatRepo struct {
	mock.Mock
}

type MockChatRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChatRepo) EXPECT() *MockChatRepo_Expecter {
	return &MockChatRepo_Expecter{mock: &_m.Mock}
}

// GetUserHistory provides a mock function for the type MockChatRepo
func (_mock *MockChatRepo) GetUserHistory(id string) ([]entity.ChatHistoryEntity, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserHistory")
	}

	var r0 []entity.ChatHistoryEntity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]entity.ChatHistoryEntity, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []entity.ChatHistoryEntity); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.ChatHistoryEntity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatRepo_GetUserHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserHistory'
type MockChatRepo_GetUserHistory_Call struct {
	*mock.Call
}

// GetUserHistory is a helper method to define mock.On call
//   - id string
func (_e *MockChatRepo_Expecter) GetUserHistory(id interface{}) *MockChatRepo_GetUserHistory_Call {
	return &MockChatRepo_GetUserHistory_Call{Call: _e.mock.On("GetUserHistory", id)}
}

func (_c *MockChatRepo_GetUserHistory_Call) Run(run func(id string)) *MockChatRepo_GetUserHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockChatRepo_GetUserHistory_Call) Return(chatHistoryEntitys []entity.ChatHistoryEntity, err error) *MockChatRepo_GetUserHistory_Call {
	_c.Call.Return(chatHistoryEntitys, err)
	return _c
}

func (_c *MockChatRepo_GetUserHistory_Call) RunAndReturn(run func(id string) ([]entity.ChatHistoryEntity, error)) *MockChatRepo_GetUserHistory_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserSimilarDocuments provides a mock function for the type MockChatRepo
func (_mock *MockChatRepo) GetUserSimilarDocuments(userID string, embedding []float32) ([]entity.ChatHistoryEntity, error) {
	ret := _mock.Called(userID, embedding)

	if len(ret) == 0 {
		panic("no return value specified for GetUserSimilarDocuments")
	}

	var r0 []entity.ChatHistoryEntity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, []float32) ([]entity.ChatHistoryEntity, error)); ok {
		return returnFunc(userID, embedding)
	}
	if returnFunc, ok := ret.Get(0).(func(string, []float32) []entity.ChatHistoryEntity); ok {
		r0 = returnFunc(userID, embedding)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.ChatHistoryEntity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, []float32) error); ok {
		r1 = returnFunc(userID, embedding)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatRepo_GetUserSimilarDocuments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserSimilarDocuments'
type MockChatRepo_GetUserSimilarDocuments_Call struct {
	*mock.Call
}

// GetUserSimilarDocuments is a helper method to define mock.On call
//   - userID string
//   - embedding []float32
func (_e *MockChatRepo_Expecter) GetUserSimilarDocuments(userID interface{}, embedding interface{}) *MockChatRepo_GetUserSimilarDocuments_Call {
	return &MockChatRepo_GetUserSimilarDocuments_Call{Call: _e.mock.On("GetUserSimilarDocuments", userID, embedding)}
}

func (_c *MockChatRepo_GetUserSimilarDocuments_Call) Run(run func(userID string, embedding []float32)) *MockChatRepo_GetUserSimilarDocuments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []float32
		if args[1] != nil {
			arg1 = args[1].([]float32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChatRepo_GetUserSimilarDocuments_Call) Return(chatHistoryEntitys []entity.ChatHistoryEntity, err error) *MockChatRepo_GetUserSimilarDocuments_Call {
	_c.Call.Return(chatHistoryEntitys, err)
	return _c
}

func (_c *MockChatRepo_GetUserSimilarDocuments_Call) RunAndReturn(run func(userID string, embedding []float32) ([]entity.ChatHistoryEntity, error)) *MockChatRepo_GetUserSimilarDocuments_Call {
	_c.Call.Return(run)
	return _c
}

// StoreConversation provides a mock function for the type MockChatRepo
func (_mock *MockChatRepo) StoreConversation(userID string, history *entity.ChatHistoryEntity, embedding []float32) (*entity.ChatHistoryEntity, error) {
	ret := _mock.Called(userID, history, embedding)

	if len(ret) == 0 {
		panic("no return value specified for StoreConversation")
	}

	var r0 *entity.ChatHistoryEntity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, *entity.ChatHistoryEntity, []float32) (*entity.ChatHistoryEntity, error)); ok {
		return returnFunc(userID, history, embedding)
	}
	if returnFunc, ok := ret.Get(0).(func(string, *entity.ChatHistoryEntity, []float32) *entity.ChatHistoryEntity); ok {
		r0 = returnFunc(userID, history, embedding)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.ChatHistoryEntity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, *entity.ChatHistoryEntity, []float32) error); ok {
		r1 = returnFunc(userID, history, embedding)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatRepo_StoreConversation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoreConversation'
type MockChatRepo_StoreConversation_Call struct {
	*mock.Call
}

// StoreConversation is a helper method to define mock.On call
//   - userID string
//   - history *entity.ChatHistoryEntity
//   - embedding []float32
func (_e *MockChatRepo_Expecter) StoreConversation(userID interface{}, history interface{}, embedding interface{}) *MockChatRepo_StoreConversation_Call {
	return &MockChatRepo_StoreConversation_Call{Call: _e.mock.On("StoreConversation", userID, history, embedding)}
}

func (_c *MockChatRepo_StoreConversation_Call) Run(run func(userID string, history *entity.ChatHistoryEntity, embedding []float32)) *MockChatRepo_StoreConversation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *entity.ChatHistoryEntity
		if args[1] != nil {
			arg1 = args[1].(*entity.ChatHistoryEntity)
		}
		var arg2 []float32
		if args[2] != nil {
			arg2 = args[2].([]float32)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockChatRepo_StoreConversation_Call) Return(chatHistoryEntity *entity.ChatHistoryEntity, err error) *MockChatRepo_StoreConversation_Call {
	_c.Call.Return(chatHistoryEntity, err)
	return _c
}

func (_c *MockChatRepo_StoreConversation_Call) RunAndReturn(run func(userID string, history *entity.ChatHistoryEntity, embedding []float32) (*entity.ChatHistoryEntity, error)) *MockChatRepo_StoreConversation_Call {
	_c.Call.Return(run)
	return _c
}
