// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package _interface

import (
	"ai-agent/entity"
	"ai-agent/handler/handler_dto"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAgentAdapter creates a new instance of MockAgentAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAgentAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAgentAdapter {
	mock := &MockAgentAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAgentAdapter is an autogenerated mock type for the AgentAdapter type
type MockAgentAdapter struct {
	mock.Mock
}

type MockAgentAdapter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAgentAdapter) EXPECT() *MockAgentAdapter_Expecter {
	return &MockAgentAdapter_Expecter{mock: &_m.Mock}
}

// Chat provides a mock function for the type MockAgentAdapter
func (_mock *MockAgentAdapter) Chat(userInput string, systemPrompt string, h []entity.ChatHistoryEntity) (*entity.ChatHistoryEntity, error) {
	ret := _mock.Called(userInput, systemPrompt, h)

	if len(ret) == 0 {
		panic("no return value specified for Chat")
	}

	var r0 *entity.ChatHistoryEntity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, []entity.ChatHistoryEntity) (*entity.ChatHistoryEntity, error)); ok {
		return returnFunc(userInput, systemPrompt, h)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, []entity.ChatHistoryEntity) *entity.ChatHistoryEntity); ok {
		r0 = returnFunc(userInput, systemPrompt, h)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.ChatHistoryEntity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, []entity.ChatHistoryEntity) error); ok {
		r1 = returnFunc(userInput, systemPrompt, h)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAgentAdapter_Chat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Chat'
type MockAgentAdapter_Chat_Call struct {
	*mock.Call
}

// Chat is a helper method to define mock.On call
//   - userInput string
//   - systemPrompt string
//   - h []entity.ChatHistoryEntity
func (_e *MockAgentAdapter_Expecter) Chat(userInput interface{}, systemPrompt interface{}, h interface{}) *MockAgentAdapter_Chat_Call {
	return &MockAgentAdapter_Chat_Call{Call: _e.mock.On("Chat", userInput, systemPrompt, h)}
}

func (_c *MockAgentAdapter_Chat_Call) Run(run func(userInput string, systemPrompt string, h []entity.ChatHistoryEntity)) *MockAgentAdapter_Chat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []entity.ChatHistoryEntity
		if args[2] != nil {
			arg2 = args[2].([]entity.ChatHistoryEntity)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAgentAdapter_Chat_Call) Return(chatHistoryEntity *entity.ChatHistoryEntity, err error) *MockAgentAdapter_Chat_Call {
	_c.Call.Return(chatHistoryEntity, err)
	return _c
}

func (_c *MockAgentAdapter_Chat_Call) RunAndReturn(run func(userInput string, systemPrompt string, h []entity.ChatHistoryEntity) (*entity.ChatHistoryEntity, error)) *MockAgentAdapter_Chat_Call {
	_c.Call.Return(run)
	return _c
}

// EmbedConverastion provides a mock function for the type MockAgentAdapter
func (_mock *MockAgentAdapter) EmbedConverastion(h *entity.ChatHistoryEntity) ([]float32, error) {
	ret := _mock.Called(h)

	if len(ret) == 0 {
		panic("no return value specified for EmbedConverastion")
	}

	var r0 []float32
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*entity.ChatHistoryEntity) ([]float32, error)); ok {
		return returnFunc(h)
	}
	if returnFunc, ok := ret.Get(0).(func(*entity.ChatHistoryEntity) []float32); ok {
		r0 = returnFunc(h)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]float32)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*entity.ChatHistoryEntity) error); ok {
		r1 = returnFunc(h)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAgentAdapter_EmbedConverastion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EmbedConverastion'
type MockAgentAdapter_EmbedConverastion_Call struct {
	*mock.Call
}

// EmbedConverastion is a helper method to define mock.On call
//   - h *entity.ChatHistoryEntity
func (_e *MockAgentAdapter_Expecter) EmbedConverastion(h interface{}) *MockAgentAdapter_EmbedConverastion_Call {
	return &MockAgentAdapter_EmbedConverastion_Call{Call: _e.mock.On("EmbedConverastion", h)}
}

func (_c *MockAgentAdapter_EmbedConverastion_Call) Run(run func(h *entity.ChatHistoryEntity)) *MockAgentAdapter_EmbedConverastion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *entity.ChatHistoryEntity
		if args[0] != nil {
			arg0 = args[0].(*entity.ChatHistoryEntity)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAgentAdapter_EmbedConverastion_Call) Return(float32s []float32, err error) *MockAgentAdapter_EmbedConverastion_Call {
	_c.Call.Return(float32s, err)
	return _c
}

func (_c *MockAgentAdapter_EmbedConverastion_Call) RunAndReturn(run func(h *entity.ChatHistoryEntity) ([]float32, error)) *MockAgentAdapter_EmbedConverastion_Call {
	_c.Call.Return(run)
	return _c
}

// EmbedMessage provides a mock function for the type MockAgentAdapter
func (_mock *MockAgentAdapter) EmbedMessage(text string) ([]float32, error) {
	ret := _mock.Called(text)

	if len(ret) == 0 {
		panic("no return value specified for EmbedMessage")
	}

	var r0 []float32
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]float32, error)); ok {
		return returnFunc(text)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []float32); ok {
		r0 = returnFunc(text)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]float32)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(text)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAgentAdapter_EmbedMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EmbedMessage'
type MockAgentAdapter_EmbedMessage_Call struct {
	*mock.Call
}

// EmbedMessage is a helper method to define mock.On call
//   - text string
func (_e *MockAgentAdapter_Expecter) EmbedMessage(text interface{}) *MockAgentAdapter_EmbedMessage_Call {
	return &MockAgentAdapter_EmbedMessage_Call{Call: _e.mock.On("EmbedMessage", text)}
}

func (_c *MockAgentAdapter_EmbedMessage_Call) Run(run func(text string)) *MockAgentAdapter_EmbedMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAgentAdapter_EmbedMessage_Call) Return(float32s []float32, err error) *MockAgentAdapter_EmbedMessage_Call {
	_c.Call.Return(float32s, err)
	return _c
}

func (_c *MockAgentAdapter_EmbedMessage_Call) RunAndReturn(run func(text string) ([]float32, error)) *MockAgentAdapter_EmbedMessage_Call {
	_c.Call.Return(run)
	return _c
}

// RecommendBookFromList provides a mock function for the type MockAgentAdapter
func (_mock *MockAgentAdapter) RecommendBookFromList(userPrompt string, systemPrompt string, b []entity.BookEntity) (*handler_dto.RecommendResponseDTO, error) {
	ret := _mock.Called(userPrompt, systemPrompt, b)

	if len(ret) == 0 {
		panic("no return value specified for RecommendBookFromList")
	}

	var r0 *handler_dto.RecommendResponseDTO
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, []entity.BookEntity) (*handler_dto.RecommendResponseDTO, error)); ok {
		return returnFunc(userPrompt, systemPrompt, b)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, []entity.BookEntity) *handler_dto.RecommendResponseDTO); ok {
		r0 = returnFunc(userPrompt, systemPrompt, b)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*handler_dto.RecommendResponseDTO)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, []entity.BookEntity) error); ok {
		r1 = returnFunc(userPrompt, systemPrompt, b)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAgentAdapter_RecommendBookFromList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecommendBookFromList'
type MockAgentAdapter_RecommendBookFromList_Call struct {
	*mock.Call
}

// RecommendBookFromList is a helper method to define mock.On call
//   - userPrompt string
//   - systemPrompt string
//   - b []entity.BookEntity
func (_e *MockAgentAdapter_Expecter) RecommendBookFromList(userPrompt interface{}, systemPrompt interface{}, b interface{}) *MockAgentAdapter_RecommendBookFromList_Call {
	return &MockAgentAdapter_RecommendBookFromList_Call{Call: _e.mock.On("RecommendBookFromList", userPrompt, systemPrompt, b)}
}

func (_c *MockAgentAdapter_RecommendBookFromList_Call) Run(run func(userPrompt string, systemPrompt string, b []entity.BookEntity)) *MockAgentAdapter_RecommendBookFromList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []entity.BookEntity
		if args[2] != nil {
			arg2 = args[2].([]entity.BookEntity)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAgentAdapter_RecommendBookFromList_Call) Return(recommendResponseDTO *handler_dto.RecommendResponseDTO, err error) *MockAgentAdapter_RecommendBookFromList_Call {
	_c.Call.Return(recommendResponseDTO, err)
	return _c
}

func (_c *MockAgentAdapter_RecommendBookFromList_Call) RunAndReturn(run func(userPrompt string, systemPrompt string, b []entity.BookEntity) (*handler_dto.RecommendResponseDTO, error)) *MockAgentAdapter_RecommendBookFromList_Call {
	_c.Call.Return(run)
	return _c
}
