// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package _interface

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockDomainUsecase creates a new instance of MockDomainUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDomainUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDomainUsecase {
	mock := &MockDomainUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDomainUsecase is an autogenerated mock type for the DomainUsecase type
type MockDomainUsecase struct {
	mock.Mock
}

type MockDomainUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDomainUsecase) EXPECT() *MockDomainUsecase_Expecter {
	return &MockDomainUsecase_Expecter{mock: &_m.Mock}
}

// GetInstructions provides a mock function for the type MockDomainUsecase
func (_mock *MockDomainUsecase) GetInstructions(n string) (string, error) {
	ret := _mock.Called(n)

	if len(ret) == 0 {
		panic("no return value specified for GetInstructions")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(n)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(n)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(n)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDomainUsecase_GetInstructions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInstructions'
type MockDomainUsecase_GetInstructions_Call struct {
	*mock.Call
}

// GetInstructions is a helper method to define mock.On call
//   - n string
func (_e *MockDomainUsecase_Expecter) GetInstructions(n interface{}) *MockDomainUsecase_GetInstructions_Call {
	return &MockDomainUsecase_GetInstructions_Call{Call: _e.mock.On("GetInstructions", n)}
}

func (_c *MockDomainUsecase_GetInstructions_Call) Run(run func(n string)) *MockDomainUsecase_GetInstructions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDomainUsecase_GetInstructions_Call) Return(s string, err error) *MockDomainUsecase_GetInstructions_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockDomainUsecase_GetInstructions_Call) RunAndReturn(run func(n string) (string, error)) *MockDomainUsecase_GetInstructions_Call {
	_c.Call.Return(run)
	return _c
}
