// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package _interface

import (
	"ai-agent/entity"

	mock "github.com/stretchr/testify/mock"
)

// NewMockBookUsecase creates a new instance of MockBookUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBookUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBookUsecase {
	mock := &MockBookUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBookUsecase is an autogenerated mock type for the BookUsecase type
type MockBookUsecase struct {
	mock.Mock
}

type MockBookUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBookUsecase) EXPECT() *MockBookUsecase_Expecter {
	return &MockBookUsecase_Expecter{mock: &_m.Mock}
}

// GetBookRecommendations provides a mock function for the type MockBookUsecase
func (_mock *MockBookUsecase) GetBookRecommendations(prompt string) ([]entity.BookEntity, error) {
	ret := _mock.Called(prompt)

	if len(ret) == 0 {
		panic("no return value specified for GetBookRecommendations")
	}

	var r0 []entity.BookEntity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]entity.BookEntity, error)); ok {
		return returnFunc(prompt)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []entity.BookEntity); ok {
		r0 = returnFunc(prompt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.BookEntity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(prompt)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookUsecase_GetBookRecommendations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookRecommendations'
type MockBookUsecase_GetBookRecommendations_Call struct {
	*mock.Call
}

// GetBookRecommendations is a helper method to define mock.On call
//   - prompt string
func (_e *MockBookUsecase_Expecter) GetBookRecommendations(prompt interface{}) *MockBookUsecase_GetBookRecommendations_Call {
	return &MockBookUsecase_GetBookRecommendations_Call{Call: _e.mock.On("GetBookRecommendations", prompt)}
}

func (_c *MockBookUsecase_GetBookRecommendations_Call) Run(run func(prompt string)) *MockBookUsecase_GetBookRecommendations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBookUsecase_GetBookRecommendations_Call) Return(bookEntitys []entity.BookEntity, err error) *MockBookUsecase_GetBookRecommendations_Call {
	_c.Call.Return(bookEntitys, err)
	return _c
}

func (_c *MockBookUsecase_GetBookRecommendations_Call) RunAndReturn(run func(prompt string) ([]entity.BookEntity, error)) *MockBookUsecase_GetBookRecommendations_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type MockBookUsecase
func (_mock *MockBookUsecase) Insert(book *entity.BookEntity) error {
	ret := _mock.Called(book)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*entity.BookEntity) error); ok {
		r0 = returnFunc(book)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBookUsecase_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockBookUsecase_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - book *entity.BookEntity
func (_e *MockBookUsecase_Expecter) Insert(book interface{}) *MockBookUsecase_Insert_Call {
	return &MockBookUsecase_Insert_Call{Call: _e.mock.On("Insert", book)}
}

func (_c *MockBookUsecase_Insert_Call) Run(run func(book *entity.BookEntity)) *MockBookUsecase_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *entity.BookEntity
		if args[0] != nil {
			arg0 = args[0].(*entity.BookEntity)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBookUsecase_Insert_Call) Return(err error) *MockBookUsecase_Insert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBookUsecase_Insert_Call) RunAndReturn(run func(book *entity.BookEntity) error) *MockBookUsecase_Insert_Call {
	_c.Call.Return(run)
	return _c
}
